name: Build_Python
on: 
  push:
    paths-ignore:
      - 'README.md'
    branches: 
      [ main ]
jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: PythonVersion
        run: |
             python --version
             pip --version

      - name: InstallCython        
        run: |
             sudo pip uninstall cython
             sudo apt-get remove cython
             pip install --upgrade pip
             pip install cython

      - name: InstallKivy        
        run: |
             pip install kivy[full] kivy_examples
             pip install kivymd

      - name: InstallCustomLibraries
        run: |
             sudo apt-get update
             sudo apt-get install libffi-dev
             pip install cffi
             pip install charset-normalizer
             sudo apt-get install libsdl2-ttf-dev
             pip install mediapipe
             
      - name: InstallBuildozer        
        run: |
             sudo apt-get install -y python3-setuptools
             pip install buildozer
             pip install https://github.com/kivy/buildozer/archive/master.zip
             git clone https://github.com/kivy/buildozer
             cd buildozer
             python setup.py build
             pip install -e .
             export PATH=~/.local/bin/:$PATH
             . ~/.bashrc
             cd ../../

      - name: Prepare        
        run: |
             cd app
             buildozer init
             python ../buildozer_spec.py
             cat buildozer.spec

      - name: Build
        run: |
             cd app
             buildozer android debug deploy

      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: DistributiveAndroid
          path: |
            app/bin/
